[project]
name = "web-diagnostic"
version = "0.1.0"
description = "Проект веб-портала для удалённой диагностики GPON"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "gunicorn>=23.0.0",
    "paramiko>=4.0.0",
    "telnetlib3>=2.0.8",
]
